# This workflow will install Python dependencies, run tests and lint with a variety of Python versions
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions

name: Build

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

env:
  GHACTIONS: ACTIVE

jobs:
  build:

    runs-on: ubuntu-latest
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
        python-version: [3.8, 3.9, '3.10', '3.11']

    steps:
    - uses: actions/checkout@v3
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v4
      with:
        python-version: ${{ matrix.python-version }}

    - name: Install python dependencies
      run: |
        python -m pip install --upgrade pip
        scripts/install

    - name: Cache Samples
      id: cache-samples
      uses: actions/cache@v3
      with:
        path: ceur-ws
        key: ceurws

    - name: getSamples
      if: steps.cache-samples.outputs.cache-hit != 'true'
      run: |
        scripts/getSamples --ceurws -p -t

    - name: saveSamples
      id: saveSamples
      uses: actions/cache/save@v3
      with:
        path: ceur-ws
        key: ceurws

    - name: Run tests
      run: |
        scripts/test
